### ISSUE TITLE
Expand all

### ISSUE THREAD

**Issue by nnddnn** [Dirkster99/XmlExplorer#1]
Please, add ExpandAll/CollapseAll methods for XPathNavigatorTreeView, to be able to expand / collapse all nodes after opening a file. Thanks!

**Comment by Dirkster99** [comment]
Hi, I have developed this a little further and the application now includes Load/Save XML and Collapse/Expand All Menu items.

For some reason I currently don't understand I am not able to expand/collapse the root node but all nodes under that. Let me know if you can see why I am not getting the root node expanded as I am really curious about what I could be missing here...? Anyways, hope this helps ...

**Comment by Dirkster99** [comment]
I was able to fix the problem with the root tag and also fixed the problem that end of tag item where not showing up previously. Would you be able to test version 1.1 ([under the Releases link](https://github.com/Dirkster99/XmlExplorer/releases)) for me and let me know if this issue can be closed, please?

**Comment by nnddnn** [comment]
Hi! The ability to see all nodes expanded is often needed when viewing a large number of similar XML, when there is no time to expand each node to see the value of a particular tag. Especially when it is on the third or fourth level of nesting. Last version 1.1 work fine, thank you!

**Comment by Dirkster99** [comment]
You are welcome - give it a STAR if you like it and let me know if you can/want contribute - be it testing, docu, developing or whatever you may like...
